### ISSUE TITLE
how to fix this issue

### ISSUE THREAD

**Issue by Nackenschelle** [G-E-N-E-S-I-S/ElevateMe#4]
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS0227	Unsicherer Code wird nur angezeigt, wenn mit /unsafe kompiliert wird.	ElevateMe	C:\Users\Martheus\Desktop\ElevateMe-master\Program.cs	12	Aktiv

**Comment by SNIKRS** [comment]
Google. It's simple to fix.
